/*var quizzes = [
    ['Quiz1',"daffodil.png",
        [
            ["apple.png",["banana","apple","watermelon","dog"],"apple"],
            ["dog.jpeg",["cat","car","whale","dog"],"dog"],
            ["cat.jpg",["cat","car","whale","dog"],"cat"],
            ["car.jpeg",["cat","car","whale","dog"],"car"],
            ["whale.jpg",["cat","car","whale","dog"],"whale"],
            ["fish.jpeg",["cat","fish","whale","dog"],"fish"],
        ]],
    ['Quiz2','cherryblossom.png',
        [
            ["pie.jpeg",["Banana","pie","watermelon","dog"],"pie"],
            ["pancakes.jpeg",["cat","pancakes","whale","dog"],"pancakes"],
            ["cat.jpg",["cat","car","whale","dog"],"cat"],
            ["car.jpeg",["cat","car","whale","dog"],"car"],
            ["whale.jpg",["cat","car","whale","dog"],"whale"],
            ["fish.jpeg",["cat","fish","whale","dog"],"fish"],
        ]],
    ['Quiz3','daisy.jpg',
        [
            ["pie.jpeg",["Banana","pie","watermelon","dog"],"pie"],
            ["pancakes.jpeg",["cat","pancakes","whale","dog"],"pancakes"],
            ["cat.jpg",["cat","car","whale","dog"],"cat"],
            ["car.jpeg",["cat","car","whale","dog"],"car"],
            ["whale.jpg",["cat","car","whale","dog"],"whale"],
            ["fish.jpeg",["cat","fish","whale","dog"],"fish"],
        ]]
]
export default quizzes;
*/
